---
title: "The significant drop in student enrolment in Ecuador: what does it mean?"
author: "Max Aantjes"
date: "15/09/2020"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**At the end of June, the IADB reported that public education enrolment in the Ecuadorian coastal provinces had increased with 6.5% (Olson, 2020). Last week, Ecuavisa, a major Ecuadorian Television Network reported that over 150 million students nationwide have transitioned from private to public institutions (Ecuavisa, 2020).**

This apparent fall in private education enrolment was entirely expected. The main driver singled out in the transition is the continued contraction of Latin American economic activity. In Ecuador, unemployment rose to 13,3% in June 2020, compared to 3,8% in December 2019 (INEC, 2020, p.15). Parents who can no longer afford private education have strong incentives to shift their child to public education, which is free. It is for similar reasons that 40% of Mexico's private institutions are expected to go bankrupt. The Ecuadorian government has attempted to intervene by reducing fees of private institutions by 25% for parents who lost their job. However, this has apparently failed to stop the widespread transition.
 
Although the driver is undisputed, it remains difficult to draw concerete conclusions from the circulating figures alone. They are not only hard to verify - since the Ecuadorian government has not made comprehensive data on this year's enrolment available - but they are also still in flux. Although the school year in the Ecuadorian Highlands and Amazon region started in September, it remains possible for parents to transfer their children from one school to another and to matriculate 'extroardinarily' until the 14th of January 2021.^[https://educacion.gob.ec/fase-de-matricula-extraordinaria-y-traslados-para-regimen-sierra-amazonia-2020-2021-inicia-el-7-de-septiembre/] The current situation may thus reverse, stabalise or even worsen in the coming months. 
Nevertheless, we can ask two crucial questions: 

~~~

*Links to the raw data are available in the corresponding [GitHub repository](https://github.com/MaxAantjes/Exp-Analysis-Dropout-EDU-EC-COVID19). To ensure reproducibility, all computations used to generate the results, as well as justifications where relevant, have been made available within the [appendix file](https://github.com/MaxAantjes/Exp-Analysis-Exclusion-EDU-EC-COV19/blob/master/appendix.md) of this repository. This written piece is part of a series of posts which are meant to be conversation starters rather than bullet-proof analyses. It hopes to inspire others to traverse beyond its inevitable limitations.*

## References

Ecuavisa (2020). *Más de 150 mil estudiantes pasaron de educación privada a fiscal en Ecuador* AVailable from: https://www.ecuavisa.com/articulo/noticias/nacional/647796-mas-150-mil-estudiantes-pasaron-educacion-privada-fiscal-ecuador

INEC (2020). *Encuesta Nacional de Empleo, Desempleo y Subempleo Telefónica*. Available from: https://www.ecuadorencifras.gob.ec/documentos/web-inec/EMPLEO/2020/ENEMDU_telefonica/Principales_Resultados_Mercado_Laboral.pdf

MINEDUC (2013). *Acuerdo No. 0067-13-A*. Available from: https://educacion.gob.ec/wp-content/uploads/downloads/2013/04/ACUERDO%20067-13.pdf

MINEDUC (2020). *Las clases en la Sierra-Amazonía 2020-2021 iniciaron desde casa*. Available from: https://educacion.gob.ec/las-clases-en-la-sierra-amazonia-2020-2021-iniciaron-desde-casa/

MINEDUC (2019). *El año escolar del régimen Sierra-Amazonía arrancará el 2 de septiembre*. Available from: https://educacion.gob.ec/el-ano-escolar-del-regimen-sierra-amazonia-arrancara-el-2-de-septiembre/

Olsen, A. S. (2020). *COVID-19 y la transición de la educación privada a la pública en Ecuador*. IADB. Available from: https://blogs.iadb.org/educacion/es/covid-19-y-la-transicion-de-la-educacion-privada-a-la-publica-en-ecuador/
